### ISSUE TITLE
Can't load ViGEmBus

### ISSUE THREAD

**Issue by ekzoss** [TheNathannator/WiitarThing#12]
Can't for the life of me get this working.. on running I get the ViGEmBus Not Found error dialogue and it exits.

I've installed the latest ViGEmBus from their page, of course, but no luck.  I've tried the version before that since the latest is pretty new, still no luck.

Can you help ?  Thanks.

**Comment by TheNathannator** [comment]
Hm, that's odd. It'll only show that if the ViGEm client library throws the exception for that. I may need to update the version of the client used, though things are supposed to be backwards-compatible.

What versions specifically did you try? And did you try restarting your PC after installing them?

**Comment by ekzoss** [comment]
same even with 1.18.367.. must be something weird just with me.. could it be missing some particular .net framework or somethin ?

**Comment by TheNathannator** [comment]
No, if you were missing any .NET Framework stuff it would tell you, and ViGEmBus and its client don't rely on that regardless. Not entirely sure what might be going wrong here.

**Comment by ekzoss** [comment]
Oh, well now I see the driver's not even loading right it seems.. from device manager:

Windows cannot load the device driver for this hardware. The driver may be corrupted or missing. (Code 39)

{Driver Entry Point Not Found}
The %hs device driver could not locate the entry point %hs in driver %hs.

**Comment by TheNathannator** [comment]
Yeah that's odd, might have to send you over to Nefarius for troubleshooting that lol

What version of Windows are you running? That's the one thing I can think of currently, never seen this particular error before.

**Comment by ekzoss** [comment]
Ya, I'll hit him up.. Windows 10, but actually it's a pretty old version, just re-imaged this machine.. I'll try again after it updates to the latest.

**Comment by ekzoss** [comment]
Ya, issue was my windows 10 build was too old.. updating to the latest did the trick.
Thanks for the help!

**Comment by TheNathannator** [comment]
Yeah I saw that in the Discord lol, glad you two were able to work it out!
