### ISSUE TITLE
Wiimote not responding to Bluetooth pair signal...

### ISSUE THREAD

**Issue by dozz-a** [TheNathannator/WiitarThing#7]
Followed all instructions in the readme. Using a genuine wiimote and les paul wiitar. On Win10 with a generic bluetooth adapter.

When I attempt to sync I receive the message:
Found Wiimote ("Nintendo RVL-CNT-01"). Attempting to pair now...
Wiimote not responding to Bluetooth pair signal...

Previously I have also seen a message along the lines of "wiitmote rejected PIN" but that is no longer showing (maybe because I updated wiitarthing). This is happening on multiple genuine wiimotes.

**Comment by TheNathannator** [comment]
I've unfortunately never run into this issue myself so I'm not sure what causes it. Once WiitarThing sends the PIN, the rest of pairing is handled by Windows and your Bluetooth receiver, so this is most likely an issue on that side of things. Do you know which Bluetooth receiver you have specifically? Based on the description of "generic", I'm assuming it's USB?

(As a side-note, the rejected PIN issue was probably fixed by a change I made to the PIN creation, previously it excluded bytes that were 0 but I removed that since it seemed safe to do so.)

**Comment by dozz-a** [comment]
Ahh, I see. Yes, its a USB receiver, this one specifically: https://www.simplecom.com.au/simplecom-nb407-usb-bluetooth-4-0-widcomm-adapter-wireless-dongle-with-a2dp-edr.html. If there's any other info I can provide to help please let me know.

**Comment by TheNathannator** [comment]
Okay, I think I have this nailed down finally after doing some more thorough technical reading lol

Looking at the specs for that receiver and re-reading the Wiibrew docs for wiimote pairing, it looks like it might not support PIN-based pairing, which wiimotes require. Given you've gotten rejected pin messages in the past though, that might not be the case, and it could be supported but just not documented.

If it isn't supported, I'm pretty sure your only options currently would be to get a new receiver that does (check if it supports HCI/Host-Controller Interface), or go for an adapter to make it wired such as the Raphnet or EMiO. The receiver I use is an [ASUS USB-BT400](https://www.asus.com/us/networking-iot-servers/adapters/all-series/usbbt400/), which does list HCI as a supported feature. You could also try the Toshiba stack method in the readme, though it's quite a bit of effort for no guarantees on if it'll work.

The Wiibrew docs do mention that pairing isn't actually required to use the wiimote, it's only required for it to reconnect to the PC on its own. I'm not sure if the available Windows APIs would allow that to be implemented into WiitarThing without making an actual kernel driver, but if it's possible then that might be an alternative down the road.

**Comment by dozz-a** [comment]
I took your advice and bought a different bluetooth receiver. Had no issues pairing with the new receiver and connection has been great. Thanks for your help!

**Comment by TheNathannator** [comment]
You're welcome, glad to help!

I'll probably add to the not-responding message to mention possible receiver incompatibility, I imagine that's what's going on the majority of the time with this.
